/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all orders. */
        get: operations["listOrders"];
        put?: never;
        /** @description Starts the Checkout Temporal saga (ADR-0006). */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch an order by id. */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cancel an order. Starts the CancelOrder workflow (ADR-0006). */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 problem document. */
        Problem: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Handle to an async Temporal workflow run.
         * @example {
         *       "id": "checkout-2c9f0b71-5d64-4a0e-9b83-0f27f7f0d001",
         *       "run_id": "019a3f8c-6d21-7c4b-8e55-0f27f7f0e001",
         *       "status": "running",
         *       "result_url": "/api/orders/2c9f0b71-5d64-4a0e-9b83-0f27f7f0d001"
         *     }
         */
        WorkflowHandle: {
            id: string;
            run_id: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed" | "cancelled";
            /**
             * Format: uri
             * @description GET to fetch terminal status + result
             */
            result_url?: string;
        };
        /** @description Request body to start a checkout. */
        CheckoutInput: {
            /** Format: uuid */
            product_id: string;
            quantity: number;
        };
        /**
         * @description A customer order.
         * @example {
         *       "id": "2c9f0b71-5d64-4a0e-9b83-0f27f7f0d001",
         *       "product_id": "6f7a1c48-1a9d-4b1e-9a2c-0f27f7f0c001",
         *       "quantity": 2,
         *       "total_cents": 259800,
         *       "status": "confirmed"
         *     }
         */
        Order: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            quantity: number;
            total_cents: number;
            /** @enum {string} */
            status: "pending" | "confirmed" | "failed" | "cancelled";
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The order list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The checkout to start. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowHandle"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the order to cancel. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowHandle"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
